print("      My Routine")
print("i wake up at 7 am")
print("i eat my breakfast at 7:20")
print("i go for running at 8 am")
print("i come back from running at 9 am")
print("i bath at 9:15 am")
print("i eat my lunch at 1 pm")
print("i do my school homework at 1:45 pm")
print("i study at 3:00 pm")
print("again i study at 5:30 pm")
print("i eat dinner at 8:00 pm")
print("i take my coding classes at 9 pm")
print("i sleep at 10:15 pm")